const IS_DEV = process.env.APP_VARIANT === 'development' || process.env.APP_VARIANT === 'preview';
// Set by eas.json's production-apk profile: per-ABI APKs + a universal one.
const ABI_SPLITS = process.env.ANDROID_ABI_SPLITS === '1';
const BASE_BUNDLE_ID = 'com.mkloouo.mmyway';
const BASE_NAME = 'Money My Way';

module.exports = {
  expo: {
    name: IS_DEV ? `${BASE_NAME} (Dev)` : BASE_NAME,
    slug: 'mmyway',
    version: '1.5.4',
    orientation: 'portrait',
    icon: './assets/icon.png',
    userInterfaceStyle: 'automatic',
    // The Dev build has a link scheme of its own: with both apps on one phone, a `mmyway://` link
    // would ask which to open, and the e2e sign-in link (src/e2e/signInLink.ts) is the Dev build's.
    scheme: IS_DEV ? 'mmyway-dev' : 'mmyway',
    plugins: [
      'expo-router',
      'expo-font',
      [
        'expo-share-intent',
        {
          iosActivationRules: { NSExtensionActivationSupportsImageWithMaxCount: 10 },
          androidIntentFilters: ['image/*'],
          disableAndroid: false,
          disableIOS: true,
        },
      ],
      '@react-native-community/datetimepicker',
      'expo-localization',
      [
        // Foreground only (#67): a position is read while Capture or the camera is open, so no
        // background permission and no foreground service go into the manifest.
        'expo-location',
        { isAndroidBackgroundLocationEnabled: false, isAndroidForegroundServiceEnabled: false },
      ],
      [
        // Assets and colours: scripts/generate-icons.py. Backgrounds are src/ui/theme.ts's bg.
        'expo-splash-screen',
        {
          image: './assets/splash/splash-light.png',
          imageWidth: 180,
          backgroundColor: '#F5F5F3',
          dark: { image: './assets/splash/splash-dark.png', backgroundColor: '#0F1013' },
        },
      ],
      [
        'expo-build-properties',
        {
          android: {
            enableMinifyInReleaseBuilds: true,
            enableShrinkResourcesInReleaseBuilds: true,
            useLegacyPackaging: true,
            // FF3 and the local receipt model are often reached over plain http:// (a LAN IP, a
            // tailnet name). Release builds block cleartext by default; only debug builds allowed it.
            usesCleartextTraffic: true,
          },
        },
      ],
      ...(ABI_SPLITS ? ['./plugins/withAbiSplits'] : []),
    ],
    ios: {
      bundleIdentifier: IS_DEV ? `${BASE_BUNDLE_ID}.dev` : BASE_BUNDLE_ID,
      icon: {
        light: './assets/icon.png',
        dark: './assets/ios/icon-dark.png',
        tinted: './assets/ios/icon-tinted.png',
      },
    },
    android: {
      adaptiveIcon: {
        foregroundImage: './assets/android/adaptive-foreground.png',
        monochromeImage: './assets/android/adaptive-foreground.png',
        backgroundColor: '#3746BB',
      },
      package: IS_DEV ? `${BASE_BUNDLE_ID}.dev` : BASE_BUNDLE_ID,
      // Coarse as well as fine: the position is asked for at "balanced" accuracy, which Android
      // can answer from the network alone if fine location is refused.
      permissions: [
        'android.permission.CAMERA',
        'android.permission.ACCESS_COARSE_LOCATION',
        'android.permission.ACCESS_FINE_LOCATION',
      ],
      // Off on purpose: the database holds every cached transaction and account balance, and
      // Android backups copy it into Google Drive. A new phone signs in and re-syncs from Firefly
      // III instead (drafts and aliases on the old phone are not carried over).
      allowBackup: false,
    },
    // Route strings like `/draft/${id}` are checked by TypeScript (types generated by expo start /
    // expo export into .expo/types, referenced from expo-env.d.ts).
    experiments: { typedRoutes: true },
    extra: {
      appVariant: process.env.APP_VARIANT ?? 'production',
      eas: {
        projectId: '88fb2848-3ae9-41a3-9952-b23a72698e6c',
      },
    },
  },
};
